# Generated by Django 6.0.5 on 2026-06-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='shift_preference',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', max_length=10),
        ),
    ]
